### ISSUE TITLE
Command line options not accepted

### ISSUE THREAD

**Issue by animetosho** [akalin/gopar#1]
Hi, thanks for this interesting new PAR1/2 implementation!

Trying it out, it seems like the `par` executable tries to parse supplied options as inputs. For example:

~~~
./par c -c 5 test.par2 par
[1/3] Loading data file "5" failed: open 5: no such file or directory
panic: open 5: no such file or directory

goroutine 1 [running]:
main.main()
        ~/go/src/github.com/akalin/gopar/cmd/par/main.go:279 +0xd60
~~~

I've tried placing the `-c 5` parameter elsewhere, as well as using `-c5` but it seems to still fail in a similar way.

I'm compiling with Go v1.10rc2 if that makes any difference.

**Comment by akalin** [comment]
Hi, looks like my help message is incorrect! You want:

```
./par -c 5 c test.par2 par
```

I'll fix the message...

**Comment by akalin** [comment]
Actually, I changed the code to put common options before the command and per-command options after the command instead. So if you update your clone, then

```
./par c -c 5 test.par2 par
```

should work. Let me know if you run into any other problems!

**Comment by animetosho** [comment]
Works great, thank you!
